config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_page#home"

  get "search", to: "static_page#search"

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :movies do
    collection do
      get :top
    end
    resources :reviews
  end

  namespace :admin do
    resources :users
    resources :movies
    resources :reviews
    resources :comments
    resources :genres
    resources :descriptions
  end
  resources :like_reviews, only: :create
  resources :watchlists, only: [:create, :destroy]
  notify_to :users

end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :set_movie
  before_action :load_genre, :load_release_year, only: :index
  before_action :admin_only

  def index
    @movies = Movie.all
    filtering_params(params).each do |key, value|
      @movies = @movies.public_send(key, value) if value.present?
    end

    @movies = @movies.paginate page: params[:page], per_page: Settings.movies.page
  end

  def show
    @reviews = Review.where(movie_id: @movie.id).order(created_at: :desc)
    @reviews.blank? ? 0 : @avg_rating = @reviews.average(:rating).round(2)
    @movie_comments = @movie.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new movie_params
    if @movie.save
      flash[:success] = t(".create_success")
      redirect_to admin_movies_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      flash[:success] = t('.update_success')
      redirect_to admin_movies_path
    else
      flash[:alert] = t(".update_failed")
      render :edit
    end
  end

  def destroy
    if @movie.destroy
      flash[:success] = t(".delete_success")
      redirect_to admin_movies_path
    else
      flash[:error] = t(".delete_failed")
    end
  end

private

  def movie_params
    params.require(:movie).permit :name, :image, :trailer, :synopsis, :release_date, :genre_id, :description_id
  end

  def set_movie
    @movie = Movie.find_by id: params[:id]
  end

  def filtering_params params
    params.permit :genre, :release_year
  end

  def load_genre
    @genres = Genre.load_data.pluck :name, :id
  end

  def load_release_year
    @release_years = Movie.order(:release_date).load_year
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :load_movie, only: :show
  before_action :load_genre, :load_release_year, :load_ratings, only: :index
  
  def index
    @movies = Movie.all
    filtering_params(params).each do |key, value|
      @movies = @movies.public_send(key, value) if value.present?
    end

    @movies = @movies.paginate page: params[:page], per_page: Settings.movies.page
  end

  def top
    @top_movies = Movie.top_by params[:type]
    @top_movies = @top_movies.paginate page: params[:page], per_page: Settings.movies.page
  end

  def show
    reviews = @movie.reviews
    reviews.blank? ? 0 : @avg_rating = reviews.average(:rating).round(2)
    @reviews = reviews.sort_reviews.paginate page: params[:page], per_page: Settings.users.page
    @like = LikeReview.new
    @add_watchlist = Watchlist.new
  end

private
  def movie_params
    params.require(:movie).permit :name, :image, :trailer, :synopsis, :release_date, :genre_id, :description_id
  end

  def filtering_params params
    params.permit :genre, :release_year, :user_rating
  end

  def load_movie
    @movie = Movie.find_by id: params[:id]
    return if @movie
    flash[:danger] = t ".not_found"
    redirect_to root_url
  end

  def load_ratings
    @ratings = Review.pluck(:rating).uniq.sort
  end

  def load_genre
    @genres = Genre.load_data.pluck :name, :id
  end

  def load_release_year
    @release_years = Movie.order(:release_date).load_year
  end
end

app/views/movies/_add_to_watchlist.html.erb
<%= form_for @add_watchlist do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.hidden_field :movie_id, value: @movie.id %>
  <span class="glyphicon glyphicon-bookmark"></span>
  <%= f.submit t(".add_watchlist") %>
<% end %>

app/views/movies/_movie.html.erb
<div class="movie" >
  <div class="movie-poster" data-toggle="tooltip" data-placement="top" title="<%= "#{t ".genre"}: #{movie.genre.name}, #{t ".year"}: #{movie.release_date.strftime("%Y")}" %>">
    <%= link_to image_tag(movie.image), movie_path(movie) %>
  </div>
  <div class="movie-title"  data-toggle="tooltip" data-placement="top" title="<%= truncate movie.synopsis, length: Settings.movies.synop_short %>">
    <%= truncate movie.name, length: Settings.movies.name_length %>
    <p>
      <span class="slabel" id="badge-review"><%= "#{movie.count_reviews} #{t ".reviews"}" %></span>
      <span class="slabel" id="badge-rated"><%= "#{movie.avg_ratings} #{t ".star"}" %></span></p>
  </div>
</div>  

app/views/movies/_properties.html.erb
<li><strong><%= t ".rating" %>: </strong>
<div class="star-rating" data-score= <%= @avg_rating %> ></div>
<em>(<%= "#{@reviews.length} reviews" %></em>)</li>

<li><strong><%= t ".genre" %>: </strong><%= @movie.genre.name %></li>

<li><strong><%= t ".premiere" %>: </strong><%= @movie.release_date %></li>

<li><strong><%= t ".length" %>: </strong><%= @movie.length %></li>

<li><strong><%= t ".director" %>: </strong><%= @movie.description.director_name %></li>

<li><strong><%= t ".cast" %>: </strong><%= @movie.description.cast_name %></li>

<li><em><%= t ".share" %></em><%= social_share_button_tag @movie.name %></li>

app/views/movies/_reviews.html.erb
<div class="user-reviews">
  <% @reviews.each do |review| %>
    <div class="media">
      <div class="media-left">
        <%= link_to gravatar_for(review.user), user_path(review.user) %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= review.user.email %>
          <small><i><%= t ".posted" %> <%= review.created_at.strftime("%B %e, %Y") %></i></small></h4>
        <div class="star-rating" data-score= <%= review.rating %> ></div>
        <h5><%= review.title %></h5>
        <p><%= truncate strip_tags(review.content), length: Settings.reviews.cont_length %></p>
        <%= link_to t(".see_more") %>
        <div class="interactive-review">
          <div class="inter-label">
            <h4><%= t ".liked" %> <span class="badge"><%= review.count_like_reviews %></span></h4>
          </div>
          <div class="inter-actions">
            <% if user_signed_in? %>
              <% unless current_user.has_review?(review) %>
                <%= form_for @like do |f| %>
                  <%= render "shared/error_messages", object: f.object %>
                  <%= f.hidden_field :review_id, value: review.id %>
                  <h5><%= t ".ask" %></h5>
                  <%= f.submit t(".yes_btn") %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="pagination">
    <%= will_paginate @reviews %>
  </div>
</div>

app/views/movies/_short_movie_info.html.erb
<li><strong><%= t ".genre" %>: </strong><%= @movie.genre.name %></li>

<li><strong><%= t ".premiere" %>: </strong><%= @movie.release_date %></li>

<li><strong><%= t ".length" %>: </strong><%= @movie.length %></li>

<li><strong><%= t ".director" %>: </strong><%= @movie.description.director_name %></li>

<li><strong><%= t ".cast" %>: </strong><%= @movie.description.cast_name %></li>

app/views/movies/_trailer.html.erb
<h3><%= t ".trailer" %></h3>

<iframe class="play-trailer" id="playTrailer" src="https://www.youtube.com/embed/<%= @movie.trailer %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen ></iframe>

app/views/movies/index.html.erb
<% provide :title, t(".browse_movies") %>

<div class="breadcrumbs">
  <%= link_to t(".home"), root_path %>
  <span><%= t ".browse_movies" %></span>
</div>
<div class="filters">
  <%= form_tag movies_path, method: "get" do %>
    <%= select_tag :genre, options_for_select(@genres), prompt: t(".genres") %>
    <%= select_tag :release_year, options_for_select(@release_years), prompt: t(".years") %>
    <%= select_tag :user_rating, options_for_select(@ratings), prompt: t(".rating") %>
    <%= submit_tag t(".filter") %>
  <% end %>
</div>
<div class="movie-list">
  <% @movies.each do |movie| %>
    <%= render partial: "movies/movie", locals: {movie: movie} %>
  <% end %>
</div>
<div class="pagination">
  <%= will_paginate @movies %>
</div>

app/views/movies/show.html.erb
<% provide :title, @movie.name %>

<div class="breadcrumbs">
  <a><%= t ".home" %></a>
  <%= link_to t(".browse"), movies_path %>
  <span><%= @movie.name %></span>
</div>
<div class="content">
  <div class="row">
    <div class="col-md-3">
      <div class="movie-poster"><%= image_tag @movie.image, class: "thumbnail" %></div>
    </div>
    <div class="col-md-5">
      <% if user_signed_in? %>
        <% unless current_user.has_watchlist?(@movie) %>
          <div class="add_watchlist">
            <%= render "add_to_watchlist" %>
          </div>
        <% end %>
      <% end %>
      <h2 class="movie-title"><%= @movie.name %></h2>
      <div class="movie-summary">
        <p><%= truncate @movie.synopsis, length: Settings.movies.synopsis_short %></p>
      </div>
      <ul class="movie-meta">
        <%= render "properties" %>
      </ul>
    </div>
  <div class="col-md-4">
    <div class="screenshots" >
      <%= render "trailer" %>
    </div>
  </div>
  </div>
  <div class="entry-content">
    <p><%= @movie.synopsis %></p>
  </div>

  <div class="wire-review-btn">
    <% if user_signed_in? %>
      <% unless current_user.has_movie?(@movie) %>
        <span class="glyphicon glyphicon-pencil"></span>
        <%= link_to t(".new_review"), new_movie_review_path(@movie), class: "btn-sm btn-primary" %>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm-8 col-md-12">
      <% if @movie.reviews.any? %>
        <h2><%= t ".user_review" %><%= " (#{@movie.count_reviews})" %></h2>
        <%= render "reviews" %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/top.html.erb
<% provide :title, t(".top") %>

<div class="row">
  <div class="col-sm-6 col-md-12">
    <div class="movie-list">
      <% @top_movies.each do |movie| %>
        <%= render partial: "movies/movie", locals: {movie: movie} %>
      <% end %>
    </div>
  </div>
  <div class="pagination">
    <%= will_paginate @top_movies %>
  </div>
</div>