config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "static_page#home"

  get "search", to: "static_page#search"

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :movies do
    collection do
      get :top
    end
    resources :reviews
  end

  namespace :admin do
    resources :users
    resources :movies
    resources :reviews
    resources :comments
    resources :genres
    resources :descriptions
  end
  resources :like_reviews, only: :create
  resources :watchlists, only: [:create, :destroy]
  notify_to :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable, :trackable, :confirmable
  has_many :interactives, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :like_reviews, dependent: :destroy
  has_many :watchlists, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  enum role: [:user, :admin]
  after_initialize :set_default_role

  scope :watchlists, ->{watchlists.order created_at: :desc}
  acts_as_target

  def has_movie? movie
    reviews.find_by movie: movie
  end

  def has_review? review
    like_reviews.find_by review: review
  end

  def has_watchlist? movie
    watchlists.find_by movie: movie
  end

  def set_default_role
    self.role ||= :user
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_only
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, flash[:success] = t(".update_success")
    else
      redirect_to admin_users_path, flash[:error] = t(".update_failed")
    end
  end

  def destroy
    if @user.destroy
    flash[:success] = t(".delete_success")
    redirect_to admin_users_path
    else
      flash[:alert] = t(".delete_failed")
    end
  end

private

  def find_user
    @user = User.find(params[:id])
    if @user.nil?
      flash[:alert] = t(".find_failed")
      redirect_to admin_users_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, :load_reviews

  def show
    @watchlists = @user.watchlists
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t ".not_found"
    redirect_to root_url
  end

  def load_reviews
    @reviews = @user.reviews.paginate page: params[:page], per_page: Settings.users.page
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = { size: Settings.gravatar.default_size }
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/users/_activity.html.erb
<div class="row">
  <div class="col-sm-6 col-md-12">
    <ul class="nav nav-tabs">
      <li class="active">
        <%= link_to "#reviews", data: {toggle: :tab} do %>
          <h4><%= "#{t ".reviews"} (#{@user.reviews.count})" %></h4>
        <% end %>
      </li>
      <% if @user == current_user %>
        <li>
          <%= link_to "#bookmarks", data: {toggle: :tab} do %>
            <h4><%= "#{t ".bookmarks"} (#{@user.watchlists.count})" %></h4>
          <% end %>
        </li>
      <% end %>
    </ul>

    <div class="tab-content">
      <div id="reviews" class="tab-pane fade in active">
        <div class="user-reviews">
          <%= render "reviews" %>
        </div>
      </div>

      <% if @user == current_user %>
        <div id="bookmarks" class="tab-pane fade">
          <div class="user-bookmarks">
            <%= render "bookmarks" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_bookmarks.html.erb
<div class="media">
  <div class="media-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <th><%= t ".movie" %></th>              
          <th><%= t ".synopsis" %></th>
          <th><%= t ".dated" %></th>
          <th><%= t ".action" %></th>              
        </thead>
        <tbody>
          <% @watchlists.each do |watchlist| %>
            <tr>
              <td>
                <%= link_to image_tag(watchlist.movie.image), movie_path(watchlist.movie), class: "media-bookmark thumbnail" %>
              </td>
              <td><p><%= truncate watchlist.movie.synopsis, length: Settings.movies.synopsis_short %></p></td>
              <td><%= (watchlist.created_at).strftime("%B %e, %Y") %></td>
              <td>
                <%= link_to t(".remove"), watchlist_path(watchlist), method: t(".delete"), data: {confirm: t(".sure")}, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow"), class: "btn btn-xs" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following? @user %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
  </div>
<% end %>

app/views/users/_info.html.erb
<div class="media">
  <div class="media-left">
    <%= gravatar_for @user %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @user.email %><br>
    <small><i><%= t ".account" %> <%= (@user.created_at).strftime("%B %e, %Y") %></i></small></h4>
    <%= link_to t(".description") %><br>
  </div>
  <div class="follow">
    <% if user_signed_in? %>
      <%= render "follow_form" %>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render "info" %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-pills">
      <li class="active">
        <%= link_to "#followers-menu", data: {toggle: :pill}, id: "followers" do %>
          <%= "#{t ".followers"} (#{@user.followers.count})" %>
        <% end %>
      </li>
      <li>
        <%= link_to "#following-menu", data: {toggle: :pill} do %>
          <%= "#{t ".following"} (#{@user.following.count})" %>
        <% end %>
      </li>
    </ul>
    <div class="tab-content">
      <div id="followers-menu" class="tab-pane fade in active">
        <div class="user-followers">
          <% if @user.followers.any? %>
            <% @user.followers.each do |user| %>
              <%= link_to gravatar_for(user, size: Settings.gravatar.size), user_path(user) %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div id="following-menu" class="tab-pane fade">
        <div class="user-following">
          <% if @user.following.any? %>
            <% @user.following.each do |user| %>
              <%= link_to gravatar_for(user, size: Settings.gravatar.size), user_path(user) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_reviews.html.erb
<% @reviews.each do |review| %>
  <div class="media">
    <div class="media-left">
      <%= link_to image_tag(review.movie.image), movie_path(review.movie), class: "media-movie thumbnail" %>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= review.movie.name %>
        <small><i><%= t ".posted" %> <%= (review.created_at).strftime("%B %e, %Y") %></i></small></h4>
      <div class="star-rating" data-score= <%= review.rating %> ></div>
      <h5><%= review.title %></h5>
      <p><%= truncate strip_tags(review.content), length: Settings.reviews.cont_length %></p>
      <%= link_to t(".see_more") %>
      <div class="interactive-review">
        <div class="inter-label">
          <h4><%= t ".liked" %> <span class="badge"><%= review.count_like_reviews %></span></h4>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="pagination">
  <%= will_paginate @reviews %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit t(".unfollow"), class: "btn btn-xs" %>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.email %>

<div class=user-site>
  <h1><%= t ".profile" %></h1>
  <div class="user-profile">
    <%= render "profile" %>
  </div>

  <h1><%= t ".activity" %></h1>
  <div class="user-activity">
    <%= render "activity" %>
  </div>
</div>